### ISSUE TITLE
There are internal error!!! 

### ISSUE THREAD

**Issue by xychensun1** [colinsheppard/time#47]
NetLogo is unable to supply you with more details about this error.  Please report the problem
at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the
contents of this window into your report.

java.lang.NoClassDefFoundError: org/joda/time/ReadablePartial
 at TimeExtension$Plus.report(TimeExtension.java:1526)
 at org.nlogo.prim._externreport.report(_externreport.java:50)
 at org.nlogo.nvm.Argument.get(Argument.java:27)
 at TimeExtension.getTimeFromArgument(TimeExtension.java:1326)
 at TimeExtension.access$500(TimeExtension.java:40)
 at TimeExtension$Show.report(TimeExtension.java:1480)
 at org.nlogo.prim._externreport.report(_externreport.java:50)
 at org.nlogo.prim.etc._monitorprecision.report(_monitorprecision.java:21)
 at org.nlogo.prim.gui._updatemonitor.perform(_updatemonitor.scala:15)
 at org.nlogo.nvm.Context.stepConcurrent(Context.java:91)
 at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.java:82)
 at org.nlogo.job.JobThread.runSecondaryJobs(JobThread.scala:178)
 at org.nlogo.job.JobThread.maybeRunSecondaryJobs(JobThread.scala:101)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply$mcV$sp(JobThread.scala:79)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76)
 at scala.util.control.Exception$Catch.apply(Exception.scala:88)
 at org.nlogo.util.Exceptions$.handling(Exceptions.scala:41)
 at org.nlogo.job.JobThread.run(JobThread.scala:75)
Caused by: java.lang.ClassNotFoundException: org.joda.time.ReadablePartial
 at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
 at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:814)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
 ... 19 more

NetLogo 5.3.1
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_74 (Oracle Corporation; 1.8.0_74-b02)
operating system: Windows 10 10.0 (amd64 processor)
Scala version 2.9.2
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: EONOERS

01:36:03.780 JobRemovedEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) JobThread
01:36:03.780 JobRemovedEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) JobThread
01:36:03.780 JobRemovedEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) JobThread
01:36:03.780 JobRemovedEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) JobThread
01:36:03.780 JobRemovedEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) JobThread
01:36:03.621 AddSliderConstraintEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
01:36:03.621 AddBooleanConstraintEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
01:36:03.610 AddSliderConstraintEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
01:36:03.610 AddSliderConstraintEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
01:36:03.610 AddSliderConstraintEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0

**Comment by colinsheppard** [comment]
@xychensun1 can you please include the netlogo code that originated this error?  Thanks!
