### ISSUE TITLE
Example models won't run in NetLogo 6.0.2

### ISSUE THREAD

**Issue by cmgoold** [colinsheppard/time#58]
I am running NetLogo version 6.0.2 on a Linux machine. I have installed the time extension but the example models that I have tried (e.g. the mouse trap model) will setup but not run. The error message I receive is below. Thanks for your help!

```
NetLogo is unable to supply you with more details about this error.  Please report the problem 
 at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the 
contents of this window into your report. 

java.lang.IllegalAccessError: tried to access field org.nlogo.agent.World.tickCounter from class time.datatypes.LogoSchedule
 at time.datatypes.LogoSchedule.getTickCounter(LogoSchedule.java:135)
 at time.datatypes.LogoSchedule.performScheduledTasks(LogoSchedule.java:156)
 at time.datatypes.LogoSchedule.performScheduledTasks(LogoSchedule.java:140)
 at time.primitives.DiscreteEventSchedulerPrimitives$Go.perform(DiscreteEventSchedulerPrimitives.java:78)
 at org.nlogo.prim._extern.perform(_extern.java:36)
 at org.nlogo.nvm.Context.stepConcurrent(Context.java:107)
 at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.scala:65)
 at org.nlogo.job.JobThread.runPrimaryJobs(JobThread.scala:133)
 at org.nlogo.job.JobThread.$anonfun$run$1(JobThread.scala:68)
 at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
 at scala.util.control.Exception$Catch.apply(Exception.scala:224)
 at org.nlogo.api.Exceptions$.handling(Exceptions.scala:41)
 at org.nlogo.job.JobThread.run(JobThread.scala:66)

NetLogo 6.0.2
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_141 (Oracle Corporation; 1.8.0_141-b15)
operating system: Linux 4.9.0-4-amd64 (amd64 processor)
Scala version 2.12.2
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: MousetrapDiscreteEvents

09:26:40.036 AddJobEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
09:26:39.964 InputBoxLoseFocusEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
09:26:39.930 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
09:26:39.930 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
09:26:39.729 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
09:26:39.729 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
09:26:39.528 JobRemovedEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) JobThread
09:26:39.464 TickStateChangeEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) JobThread
09:26:39.441 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
09:26:39.441 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
```

**Comment by Westlife1002** [comment]
hi,
is this issue fixed? how reliable this extension is? I am interested to apply some forms of discrete event modelling paradigm inside my ABS model using Netlogo

**Comment by robwalton** [comment]
The issue still exists with netlogo 6.1. I've tried it with netlogo 6.0 and there is no problem. When using netlogo > 6.0 netlogo reports that the extension was built against 6.0 and may not work. **I'll try rebuilding it against 6.1 and see what happens**.

For reference, the exception reported above

    java.lang.IllegalAccessError: tried to access field org.nlogo.agent.World.tickCounter from class time.datatypes.LogoSchedule

occurs with the following when calling `time:go`:

    clear-all
    crt 1
    time:schedule-event turtles [ [] -> fd 1 ] 1.0
    time:go
